title: A Stronger OpenGL Blur
author: Sebastian Greis
email: spiritusbrenner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Achieve a stronger blur effect in OpenGL by applying the blur shader at a lower resolution than the original image

# social links
twitter_username: OpDarkside # DO NOT include the @ character, or else the build will fail!
github_username:  OperationDarkside # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
